### ISSUE TITLE
How to Extract(host(url), username, password)?

### ISSUE THREAD

**Issue by secfb** [nnposter/nndefaccts#12]
The tool you wrote is really beautiful. How can we save the default information as host(url), username, password in a file. Internal network tests can yield a lot of results. It is really difficult to extract this result.
**Sample output**
```
url,username,password
http://10.2.14.221:80,admin,123456
http://10.1.3.52:8087/manager/html,admin,123456
```

**Comment by secfb** [comment]
https://github.com/InfosecMatter/default-http-login-hunter

**Comment by nnposter** [comment]
NNdefaccts is a fingerprint dataset, which represents the expertise of recognizing various applications and devices and the logic of testing them for default credentials. It is designed to be used together with [Nmap](https://nmap.org/). On the other hand, [default-http-login-hunter](https://github.com/InfosecMatter/default-http-login-hunter) is a simple shell wrapper around these two core components, written by another party.

If you would like a different output from this wrapper then you should place the ask with that project. If you are instead asking how to obtain the results from Nmap in a machine-parsed format then you should consider using option `-oX`, which allows you to get the data [structured as XML](https://nmap.org/book/output-formats-xml-output.html). The output would contain structures like this:
```xml
<table key="Cacti">
  <elem key="cpe">cpe:/a:cacti:cacti</elem>
  <elem key="path">/</elem>
  <table key="credentials">
    <table>
      <elem key="username">admin</elem>
      <elem key="password">admin</elem>
    </table>
  </table>
</table>
<table key="Nagios">
  <elem key="cpe">cpe:/a:nagios:nagios</elem>
  <elem key="path">/nagios/</elem>
  <table key="credentials">
    <table>
      <elem key="username">nagiosadmin</elem>
      <elem key="password">CactiEZ</elem>
    </table>
  </table>
</table>
```
It then takes only a few lines of script to convert the XML to CSV or other formats as needed.

**Comment by secfb** [comment]
Thank you for the information. I will try to write my own script.
