### ISSUE TITLE
Dell iDRAC6/7 (Mbedthis): doesn't work on HTTP

### ISSUE THREAD

**Issue by cnotin** [nnposter/nndefaccts#4]
Dell iDRAC 6/7 seems to be listening by default on HTTP and HTTPS. HTTP is only a redirection to HTTPS and doesn't accept authentication requests.
Currently we get this which isn't very neat:
```
PORT    STATE SERVICE REASON
80/tcp  open  http    syn-ack ttl 128
| http-default-accounts: 
|   [Dell iDRAC6/7 (Mbedthis)] at /
|_    (no valid default credentials found)
443/tcp open  https   syn-ack ttl 128
| http-default-accounts: 
|   [Dell iDRAC6/7 (Mbedthis)] at /
|_    root:calvin
```

I have a few ideas to improve this but nothing that satisfies me 100%. Maybe you'll have better ones :)

**Comment by nnposter** [comment]
This should not be that hard. We can just check that some other resource responds with HTTP 200, instead of a redirect or an error.

**Comment by cnotin** [comment]
It works, thanks :)
```
PORT    STATE SERVICE REASON
80/tcp  open  http    syn-ack ttl 128
443/tcp open  https   syn-ack ttl 128
| http-default-accounts: 
|   [Dell iDRAC6/7 (Mbedthis)] at /
|_    root:calvin
```
